import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Fouter from "@/components/fouter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Scarlet's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <main className="flex-1">{children}</main>
          <Fouter/>
        </ThemeProvider>
      </body>
    </html>
  );
}
